baseURL = "https://docs.blankdash.com/"
languageCode = "en-us"
title = "RTFM"
theme = "hextra"

enableRobotsTXT = true

[markup]
  [markup.highlight]
    noClasses = false

  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true

# keep directory structure on publish
uglyURLs = false              # creates foo/bar/index.html, not foo/bar.html

[permalinks]
  default = "/:sections/:filename/"